name: Wisen
favicon: null
layout_spectrum: 1
typography_spectrum: 0.37252
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#13140f'
    - '#87826d'
    - '#e5e7dc'
    - '#363b35'
    - '#b8b6a0'
  brandStrength: 0.22452024556696415
  lightness: 0.16361066652461886
  saturation: 0.8551753528881818
  rhythmicContrast: 0.644250244833529
purpose: []
